-- ============================================================
-- ESTRUCTURA DE BASE DE DATOS
-- Tablas compatibles con PostgreSQL / Supabase y con los modelos actuales
-- ============================================================

-- ----------------------------
-- Tabla: personas
-- ----------------------------
DROP TABLE IF EXISTS personas CASCADE;
CREATE TABLE personas (
    cedula       INTEGER PRIMARY KEY,
    nombres      VARCHAR(100) NOT NULL,
    apellidos    VARCHAR(100) NOT NULL,
    telefono     INTEGER,
    direccion    VARCHAR(255),
    nacionalidad VARCHAR(3),
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ----------------------------
-- Tabla: roles
-- ----------------------------
DROP TABLE IF EXISTS roles CASCADE;
CREATE TABLE roles (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    observacion  VARCHAR(255),
    estado       INTEGER NOT NULL,
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ----------------------------
-- Tabla: permisos
-- ----------------------------
DROP TABLE IF EXISTS permisos CASCADE;
CREATE TABLE permisos (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(100) NOT NULL,

    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ----------------------------
-- Tabla: permisos_roles
-- ----------------------------
DROP TABLE IF EXISTS permisos_roles CASCADE;
CREATE TABLE permisos_roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crear       BOOLEAN NOT NULL,
    editar      BOOLEAN NOT NULL,
    eliminar    BOOLEAN NOT NULL,
    leer        BOOLEAN NOT NULL,
    id_permisofk INTEGER NOT NULL,
    id_rolfk     INTEGER NOT NULL,
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_permisos_roles_permiso FOREIGN KEY (id_permisofk) REFERENCES permisos (id),
    CONSTRAINT fk_permisos_roles_rol     FOREIGN KEY (id_rolfk)     REFERENCES roles (id)
);

-- ----------------------------
-- Tabla: marcas
-- ----------------------------
DROP TABLE IF EXISTS marcas CASCADE;
CREATE TABLE marcas (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    estado      INTEGER NOT NULL,

    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ----------------------------
-- Tabla: categorias
-- ----------------------------
DROP TABLE IF EXISTS categorias CASCADE;
CREATE TABLE categorias (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50) NOT NULL,
    descripcion  VARCHAR(255),
    fecha_edit   TIMESTAMP WITH TIME ZONE,
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    estado       INTEGER NOT NULL
);

-- ----------------------------
-- Tabla: precios
-- ----------------------------
DROP TABLE IF EXISTS precios CASCADE;
CREATE TABLE precios (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto        NUMERIC NOT NULL,
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    valido_desde TIMESTAMP WITH TIME ZONE NOT NULL,
    valido_hasta TIMESTAMP WITH TIME ZONE
);

-- ----------------------------
-- Tabla: productos
-- ----------------------------
DROP TABLE IF EXISTS productos CASCADE;
CREATE TABLE productos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    descripcion     VARCHAR(255),
    estado          INTEGER NOT NULL,
    impuesto        INTEGER NOT NULL,
    pesable         BOOLEAN NOT NULL DEFAULT FALSE,
    perecedero      BOOLEAN NOT NULL DEFAULT FALSE,
    costeo          INTEGER,
    unidad_medida   VARCHAR(25) NOT NULL,
    es_ingrediente  BOOLEAN,
    es_comida       BOOLEAN,
    id_categoriafk    INTEGER NOT NULL,
    id_marcafk        INTEGER NOT NULL,
    fecha_creado    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_edit      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_productos_categoria FOREIGN KEY (id_categoriafk) REFERENCES categorias (id),
    CONSTRAINT fk_productos_marca     FOREIGN KEY (id_marcafk)     REFERENCES marcas (id)
);

-- ----------------------------
-- Tabla: detalle_producto
-- ----------------------------
DROP TABLE IF EXISTS detalle_producto CASCADE;
CREATE TABLE detalle_producto (
    cod_barra       VARCHAR(15) PRIMARY KEY,
    unidad_por_lote INTEGER NOT NULL,
    color           VARCHAR(50),
    tamanho         INTEGER,
    id_productofk     INTEGER NOT NULL,
    fecha_creado    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_detalle_producto_producto FOREIGN KEY (id_productofk) REFERENCES productos (id)
);

-- ----------------------------
-- Tabla: detalles_precio
-- ----------------------------
DROP TABLE IF EXISTS detalles_precio CASCADE;
CREATE TABLE detalles_precio (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_productofk           INTEGER NOT NULL,
    id_preciofk             INTEGER NOT NULL,
    detalle_producto_cod  VARCHAR(15) NOT NULL,
    fecha_creado          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_detalles_precio_producto FOREIGN KEY (id_productofk) REFERENCES productos (id),
    CONSTRAINT fk_detalles_precio_precio    FOREIGN KEY (id_preciofk)   REFERENCES precios (id),
    CONSTRAINT fk_detalles_precio_detalle_producto FOREIGN KEY (detalle_producto_cod) REFERENCES detalle_producto (cod_barra)
);

-- ----------------------------
-- Tabla: ingredientes
-- ----------------------------
DROP TABLE IF EXISTS ingredientes CASCADE;
CREATE TABLE ingredientes (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad               INTEGER NOT NULL,
    unidad_medida          VARCHAR(25) NOT NULL,
    id_producto_ingredientefk INTEGER NOT NULL,
    id_producto_finalfk      INTEGER NOT NULL,
    fecha_creado           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ingredientes_producto_ingrediente FOREIGN KEY (id_producto_ingredientefk) REFERENCES productos (id),
    CONSTRAINT fk_ingredientes_producto_final      FOREIGN KEY (id_producto_finalfk)      REFERENCES productos (id)
);

-- ----------------------------
-- Tabla: usuarios
-- ----------------------------
DROP TABLE IF EXISTS usuarios CASCADE;
CREATE TABLE usuarios (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contra        VARCHAR(255) NOT NULL,
    alias         VARCHAR(75) NOT NULL,
    estado        INTEGER NOT NULL,

    fecha_creado  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    id_rolfk      INTEGER NOT NULL,
    id_personafk  INTEGER NOT NULL,
    CONSTRAINT fk_usuarios_rol    FOREIGN KEY (id_rolfk)    REFERENCES roles (id),
    CONSTRAINT fk_usuarios_persona FOREIGN KEY (id_personafk) REFERENCES personas (cedula)
);

-- ----------------------------
-- Tabla: proveedores
-- ----------------------------
DROP TABLE IF EXISTS proveedores CASCADE;
CREATE TABLE proveedores (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_personafk   INTEGER NOT NULL,
    razon_social   VARCHAR(255) NOT NULL,
    ruc            INTEGER NOT NULL,
    correo         VARCHAR(50),
    estado         BOOLEAN NOT NULL,
    fecha_creado   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_edit     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_proveedores_persona FOREIGN KEY (id_personafk) REFERENCES personas (cedula)
);

-- ----------------------------
-- Tabla: clientes
-- ----------------------------
DROP TABLE IF EXISTS clientes CASCADE;
CREATE TABLE clientes (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_personafk   INTEGER NOT NULL,
    ruc            INTEGER,
    razon_social   VARCHAR(255),
    persona_fisica INTEGER NOT NULL,
    fecha_creado   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_clientes_persona FOREIGN KEY (id_personafk) REFERENCES personas (cedula)
);

-- ----------------------------
-- Tabla: vendedores
-- ----------------------------
DROP TABLE IF EXISTS vendedores CASCADE;
CREATE TABLE vendedores (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salario        NUMERIC NOT NULL,
    comision       NUMERIC,
    estado         BOOLEAN NOT NULL,
    fecha_creado   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_edit     TIMESTAMP WITH TIME ZONE,
    id_personafk   INTEGER NOT NULL,
    CONSTRAINT fk_vendedores_persona FOREIGN KEY (id_personafk) REFERENCES personas (cedula)
);

-- ----------------------------
-- Tabla: locales
-- ----------------------------
DROP TABLE IF EXISTS locales CASCADE;
CREATE TABLE locales (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    direccion     VARCHAR(255),
    telefono      VARCHAR(50),
    estado        BOOLEAN NOT NULL,
    fecha_creado  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_edit    TIMESTAMP WITH TIME ZONE
);

-- ----------------------------
-- Tabla: mesas
-- ----------------------------
DROP TABLE IF EXISTS mesas CASCADE;
CREATE TABLE mesas (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50) NOT NULL,
    estado       BOOLEAN NOT NULL,
    id_localfk   INTEGER NOT NULL,
    fecha_creado TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mesas_local FOREIGN KEY (id_localfk) REFERENCES locales (id)
);

-- ----------------------------
-- Tabla: stocks
-- ----------------------------
DROP TABLE IF EXISTS stocks CASCADE;
CREATE TABLE stocks (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cant_deposito        INTEGER NOT NULL,
    cant_mostrador       INTEGER NOT NULL,
    precio               NUMERIC NOT NULL,
    cant_reservado       INTEGER NOT NULL,
    lote                 VARCHAR(100),
    fecha_vencimiento    TIMESTAMP WITH TIME ZONE,
    id_detalleProductofk VARCHAR(15) NOT NULL,
    id_localfk           INTEGER NOT NULL,
    fecha_creado         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_stocks_detprod FOREIGN KEY (id_detalleProductofk) REFERENCES detalle_producto (cod_barra),
    CONSTRAINT fk_stocks_local   FOREIGN KEY (id_localfk)           REFERENCES locales (id)
);

-- ----------------------------
-- Tabla: cajas
-- ----------------------------
DROP TABLE IF EXISTS cajas CASCADE;
CREATE TABLE cajas (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creado   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_cierre   TIMESTAMP WITH TIME ZONE,
    monto_apertura NUMERIC NOT NULL,
    monto_cierre   NUMERIC,
    id_usuariofk   INTEGER NOT NULL,
    CONSTRAINT fk_cajas_usuario FOREIGN KEY (id_usuariofk) REFERENCES usuarios (id)
);

-- ----------------------------
-- Tabla: ventas
-- ----------------------------
DROP TABLE IF EXISTS ventas CASCADE;
CREATE TABLE ventas (
    id_venta         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro              VARCHAR(10),
    fecha            TIMESTAMP WITH TIME ZONE NOT NULL,
    estado           INTEGER NOT NULL,
    cod_usuariofk_edit BOOLEAN,
    fecha_edit       TIMESTAMP WITH TIME ZONE,
    empresa_id       INTEGER,
    clima            INTEGER,
    temperatura      INTEGER,
    humedad          INTEGER,
    evento           BOOLEAN,
    id_usuariofk     INTEGER NOT NULL,
    id_clientefk     INTEGER NOT NULL,
    id_localfk       INTEGER NOT NULL,
    fecha_creado     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ventas_usuario FOREIGN KEY (id_usuariofk) REFERENCES usuarios (id),
    CONSTRAINT fk_ventas_cliente FOREIGN KEY (id_clientefk) REFERENCES clientes (id),
    CONSTRAINT fk_ventas_local   FOREIGN KEY (id_localfk)   REFERENCES locales (id)
);

-- ----------------------------
-- Tabla: detalle_venta
-- ----------------------------
DROP TABLE IF EXISTS detalle_venta CASCADE;
CREATE TABLE detalle_venta (
    id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad         INTEGER NOT NULL,
    precio           NUMERIC NOT NULL,
    descuento        NUMERIC,
    id_productofk    INTEGER NOT NULL,
    id_ventafk       INTEGER NOT NULL,
    fecha_creado     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_detventa_producto FOREIGN KEY (id_productofk) REFERENCES productos (id),
    CONSTRAINT fk_detventa_venta    FOREIGN KEY (id_ventafk)    REFERENCES ventas (id_venta)
);

-- ----------------------------
-- Tabla: compras
-- ----------------------------
DROP TABLE IF EXISTS compras CASCADE;
CREATE TABLE compras (
    id_compra      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nro            VARCHAR(10),
    id_localfk     INTEGER NOT NULL,
    id_clientefk   INTEGER NOT NULL,
    fecha          TIMESTAMP WITH TIME ZONE NOT NULL,
    estado         INTEGER NOT NULL,
    fecha_creado   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_edit     TIMESTAMP WITH TIME ZONE,
    id_proveedorfk INTEGER NOT NULL,
    CONSTRAINT fk_compras_local     FOREIGN KEY (id_localfk)     REFERENCES locales (id),
    CONSTRAINT fk_compras_cliente   FOREIGN KEY (id_clientefk)   REFERENCES clientes (id),
    CONSTRAINT fk_compras_proveedor FOREIGN KEY (id_proveedorfk) REFERENCES proveedores (id)
);

-- ----------------------------
-- Tabla: detalle_compra
-- ----------------------------
DROP TABLE IF EXISTS detalle_compra CASCADE;
CREATE TABLE detalle_compra (
    id_detalle_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad          INTEGER NOT NULL,
    precio            NUMERIC NOT NULL,
    id_comprafk       INTEGER NOT NULL,
    id_productofk     INTEGER NOT NULL,
    fecha_creado      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_detcompra_compra   FOREIGN KEY (id_comprafk)   REFERENCES compras (id_compra),
    CONSTRAINT fk_detcompra_producto FOREIGN KEY (id_productofk) REFERENCES productos (id)
);
